[project]
name = "ded-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dedalus>=3.0.3",
    "marimo>=0.14.13",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
]
